Vagrant.configure("2") do |config|
    config.vm.box = "mrvantage/centos7-minikube"
  
    # minikube_server VM
    config.vm.define "minikube" do |minikube|
      minikube.vm.provider "virtualbox" do |vb|
        vb.memory = "5096"
        vb.name = "minik8s"
        vb.cpus = "4"
      end
      minikube.vm.network "private_network", ip: "192.168.10.11"
      minikube.vm.hostname = "minikube"
    end
  
  
  
  end